version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1
    networks:
      - webnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  service:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./service:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - postgres
  ui:
    container_name: ui
    networks:
      - webnet
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - "8080:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  webnet:
volumes:
  pgdata: