FROM node:12.20.0-alpine3.10

EXPOSE 8080 

RUN mkdir -p /app/public /app/src
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY tsconfig.json /app/tsconfig.json
COPY package*.json /app/

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]